# Base image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy source code
COPY . .

# Expose React dev server port
EXPOSE 8080

# Force React to start on 8080
ENV PORT=8080

# Start React in development mode
CMD ["npm","start"]