# Base image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy source code
COPY . .

# Expose React dev server port
EXPOSE 3000

# Start React in development mode
CMD ["npm","start"]